vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       jewelry_images:
           uri_prefix: /images/jewelry
           upload_destination: '%kernel.project_dir%/public/images/jewelry'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
